service: lambda-wer
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

functions:
  wer:
    handler: handler.wer
    events:
      - http:
          path: /wer
          method: post
          cors: true

custom:
  pythonRequirements:
    zip: true
    slim: true

plugins:
  - serverless-python-requirements
  - serverless-offline
